version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: auth-nestjs-mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nestjs_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    networks:
      - auth-nestjs-network
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: auth-nestjs-phpmyadmin
    environment:
      PMA_HOST: auth-nestjs-mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '8080:80'
    networks:
      - auth-nestjs-network

networks:
  auth-nestjs-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
